### ISSUE TITLE
Error getting up and running (Windows)

### ISSUE THREAD

**Issue by liamwh** [rust-awesome-app/awesome-app#2]
Hi Jeremy,

Firstly, nice software! It looks great and I can't wait to get started playing around with it. Unfortunately, I've encountered the below error when trying to get awesome-app up and running with `awesome-app dev`. It opens the Tauri window but the screen is completely blank, also if navigating to http://localhost:8080.

I am running Windows 10 `19044.2130`, and Node version `v18.12.1` and npm version `8.19.2`

Can you help me out by steering me in the right direction by any chance?

I have a link from C:\Users\Liam\Git to C:\Git in case you were expecting the mixed paths to be strange and/or problematic.

```
bundles ./src-ui/src/main.ts → dist/js/app-bundle.js...
pcss-cli - css file generated - C:\Users\Liam\Git\my-awesome-app\dist\css\app-bundle.css
pcss-cli - css map  generated - C:\Users\Liam\Git\my-awesome-app\dist\css\app-bundle.css.map
[!] RollupError: Unexpected token (Note that you need plugins to import files that are not JavaScript)
../../../../Git/my-awesome-app/src-ui/src/main.ts (19:46)
17:   // (similar to what loadDefaultIcons does for @dom-native/ui icons)
18:   // (this allows to use the <use xlink:href="#symbol_id" ...> and update fill from css)
19:   const svgEl = html(SYMBOLS).firstElementChild!;
                                                   ^
20:   svgEl.setAttribute('style', 'display: none'); // in case dom engine move it to body
21:   document.head.appendChild(svgEl);
RollupError: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (C:\Git\my-awesome-app\node_modules\rollup\dist\shared\rollup.js:206:30)
    at Module.error (C:\Git\my-awesome-app\node_modules\rollup\dist\shared\rollup.js:13346:16)
    at Module.tryParse (C:\Git\my-awesome-app\node_modules\rollup\dist\shared\rollup.js:13720:25)
    at Module.setSource (C:\Git\my-awesome-app\node_modules\rollup\dist\shared\rollup.js:13630:24)
    at ModuleLoader.addModuleSource (C:\Git\my-awesome-app\node_modules\rollup\dist\shared\rollup.js:22949:20)


[2022-11-06 15:19:16] waiting for changes...

> my-awesome-app-base@0.9.15 tauri
> tauri dev

        Info Watching C:\Users\Liam\Git\my-awesome-app\src-tauri for changes...
   Compiling tauri v1.1.1
   Compiling tauri-macros v1.1.1
   Compiling app v0.1.0 (C:\Users\Liam\Git\my-awesome-app\src-tauri)
    Finished dev [unoptimized + debuginfo] target(s) in 14.07s
```

**Comment by liamwh** [comment]
Using a Mac now 🤷‍♂️
